In [4]:
import numpy as np

In [5]:
# 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [17]:
# 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
# 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
m = np.random.randint(1, 11, (5, 5))
print(m)

[[ 3  8  3  2  5]
 [ 3  3 10  9 10]
 [ 9  3  1  1  4]
 [ 5  6  1  5 10]
 [ 8  2  2  7  9]]


In [16]:
# 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
m = np.random.randint(0, 2, (4, 4))
print(m)

[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 0 0 0]]


In [24]:
# 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
first = np.random.randint(1, 11, (5))
second = np.random.randint(1, 11, (5))
addition_result = first + second
subtraction_result = first - second
multiplication_result = first * second


[10 11 10 18  5]
[ 0  3 -4  0  3]
[25 28 21 81  4]


In [25]:
# 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
first = np.random.randint(1, 11, (7))
second = np.random.randint(1, 11, (7))
result = np.dot(first, second)
print(result)

224


In [29]:
# 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
first = np.random.randint(1, 11, (2, 2))
second = np.random.randint(1, 11, (2, 3))
result = np.dot(first, second)
print(result)

[[ 21  20  13]
 [107 105  81]]


In [30]:
# 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
m = np.random.randint(1, 11, (3, 3))
a_inv = np.linalg.inv(m)
print(a_inv)


[[-0.45762712 -0.01694915  0.52542373]
 [ 0.16101695  0.13559322 -0.20338983]
 [ 0.38135593 -0.15254237 -0.27118644]]


In [32]:
# 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
m = np.random.randint(0, 2, (4, 4))
print(m)
result = m.T
print(result)

[[0 0 1 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 1 1]]
[[0 0 0 0]
 [0 0 1 0]
 [1 0 0 1]
 [0 0 0 1]]


In [34]:
# 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, (4))
result = np.dot(matrix, vector)
print(result)

[152 196 184]


In [35]:
# 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix = np.random.randint(1, 11, (2, 3))
vector = np.random.randint(1, 11, (3))
result = np.dot(matrix, vector)
print(result)


[133 182]


In [40]:
# 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
result = np.multiply(matrix1, matrix2)
print(result)

[[80 16]
 [ 2 32]]


In [41]:
# 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
result = np.dot(matrix1, matrix2)
print(result)

[[77 59]
 [62 60]]


In [43]:
# 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix = np.random.randint(1, 101, (5, 5))
result = np.sum(matrix)
print(result)

1174


In [44]:
# 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))
result = matrix1 - matrix2
print(result)

[[-3 -1  7 -3]
 [ 1  1  3 -4]
 [ 3 -6 -3 -1]
 [ 0  5  0  3]]


In [46]:
# 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.random.rand(3, 3)
row_sums = np.sum(matrix, axis=1)
result = row_sums.reshape(3, 1)
print(result)

[[0.6134709 ]
 [1.58575935]
 [0.69349027]]


In [48]:
# 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(1, 11, (3, 4))
result = np.square(matrix)
print(result)

[[36  4 81  1]
 [25 16 81  1]
 [ 1  1 81 64]]


In [5]:
# 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
vector = np.random.randint(1, 51, 4)
result = np.sqrt(vector)
print(result)

[4.24264069 4.89897949 5.29150262 6.70820393]
