In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [26]:
def regression(x, y):
    return x[0] + x[1] * y
result = regression(np.array([4, 2]), np.array([3, 5]))
result

array([10, 14])

In [28]:
def mean_squared_error(a, b, c):
    m = len(b)  
    predictions = regression(a, b)  
    mse = np.sum((predictions - c)**2) / m
    return mse

b = np.array([1, 2, 3, 4, 5]) 
c = np.array([3, 3, 4, 4, 5]) 
a = np.array([0.0, 0.0])

loss = mean_squared_error(a, b, c)
loss

15.0

In [43]:
def gradient_descent_step(a, b, c, learning_rate):
    m = len(x)   
    gradient_w0 = (1/m) * np.sum(regression(a, b) - c)
    gradient_w1 = (1/m) * np.sum((regression(a, b) - c) * x)   
    w[0] -= learning_rate * gradient_w0
    w[1] -= learning_rate * gradient_w1
    return w
b = np.array([1, 2, 3, 4, 5])  
c = np.array([3, 3, 4, 4, 5]) 
a = np.array([0.0, 0.0])  
learning_rate = 0.01
result = gradient_descent_step(a, b, c, learning_rate)
result

array([3.78838754e+02, 4.06820282e+05, 1.38604950e+06])

In [37]:
df = pd.read_csv('Housing.csv')
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [38]:
X = df[['area', 'bedrooms', 'bathrooms']]
y = df['price']

model = LinearRegression()
model.fit(X, y)

w = model.coef_
w

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])

In [39]:
X = df[['area', 'bedrooms', 'bathrooms']]
y = df['price']

X = X.copy()
X['bias'] = 1

w1 = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w1 = w1[:-1] 

w1

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])